moditect/moditect

core/src/main/java/org/moditect/commands/AddModuleInfo.java
integrationtest/undertow/pom.xml

fix maven config
existing files weren't replaced

Correct issues preventing the build

---

core/pom.xml
core/src/main/java/org/moditect/internal/compiler/ModuleInfoCompiler.java

Upgrade to latest ASM release 6.2.1

---

core/src/main/java/org/moditect/commands/GenerateModuleInfo.java
core/src/main/java/org/moditect/internal/compiler/ModuleInfoCompiler.java
parent/pom.xml

Well, I guess we're not lying about "breaking things between releases." I'll add some comments explaining why.

Update JavaParser to 3.9.1

---

core/src/main/java/org/moditect/commands/GenerateModuleInfo.java
core/src/main/java/org/moditect/internal/compiler/ModuleInfoCompiler.java

Here you go. All I can say is: it builds :-)

Upgrade JP

---

core/src/main/java/org/moditect/commands/CreateRuntimeImage.java
maven-plugin/src/main/java/org/moditect/mavenplugin/image/CreateRuntimeImageMojo.java

Simple modification to support '--no-header-files' and '--no-man-pages'.

Support for '--no-header-files' and '--no-man-pages'

---

core/src/main/java/org/moditect/model/PackageNamePattern.java

Fixes (or at least it tries to fix) #148

#148 Support multiple export modules TOs

---

core/src/main/java/org/moditect/commands/GenerateModuleInfo.java
core/src/main/java/org/moditect/commands/GenerateModuleList.java
core/src/main/java/org/moditect/internal/command/LogWriter.java

Redirect jdeps output to Moditect Log

---

maven-plugin/src/main/java/org/moditect/mavenplugin/add/AddModuleInfoMojo.java

#151: Use project.build.fileName to resolve default JAR

---

maven-plugin/src/main/java/org/moditect/mavenplugin/add/AddModuleInfoMojo.java

Add support for dependency exclusion

---

README.md
maven-plugin/src/main/java/org/moditect/mavenplugin/add/AddModuleInfoMojo.java

#179 Check if a JAR is already modular before enhancing it

---

README.md
core/src/main/java/org/moditect/Moditect.java
core/src/main/java/org/moditect/commands/AddModuleInfo.java
core/src/test/java/org/moditect/test/AddModuleInfoTest.java
maven-plugin/src/main/java/org/moditect/mavenplugin/add/AddModuleInfoMojo.java

#185 Add outputTimestamp property for reproducible builds

---

core/src/main/java/org/moditect/commands/AddModuleInfo.java

fixes #199
checked on jackson-databind

set last access and create times

---

.github/workflows/release.yml
core/pom.xml
maven-plugin/pom.xml
parent/pom.xml

@gunnarmorling the following GH secrets must be added to this repository
```
JRELEASER_NEXUS2_USERNAME
JRELEASER_NEXUS2_PASSWORD
JRELEASER_GPG_PASSPHRASE
JRELEASER_GPG_PUBLIC_KEY
JRELEASER_GPG_SECRET_KEY
```
Details at https://jreleaser.org/guide/latest/examples/maven/maven-central.html#_maven
Fixes #217

#217 Configure JReleaser for deployments to Maven Central

---

core/pom.xml
parent/pom.xml

[#223] don't use directory plugin

---

parent/pom.xml

Better merge https://github.com/moditect/moditect/pull/224 => #224 first

[CHORE] update parent

---

parent/pom.xml

[#226] update to asm 9.6 for Java 22 support

---

core/src/main/java/org/moditect/commands/CreateRuntimeImage.java
maven-plugin/src/main/java/org/moditect/mavenplugin/image/CreateRuntimeImageMojo.java

#213 Support additional values for compress when creating a runtime image

---

maven-plugin/src/main/java/org/moditect/mavenplugin/image/CreateRuntimeImageMojo.java

#216 create-runtime-image: Error message on missing artifact

---

core/src/main/java/org/moditect/internal/compiler/ModuleInfoCompiler.java

This is one potential semi-resolution to #249

Only use inner class heuristic with class names

---

.github/workflows/release.yml
core/pom.xml
core/src/main/java/org/moditect/commands/AddModuleInfo.java
core/src/test/java/org/moditect/test/AddModuleInfoTest.java
maven-plugin/pom.xml
maven-plugin/src/main/java/org/moditect/mavenplugin/add/AddModuleInfoMojo.java
parent/pom.xml

- reword commit messages to follow conventional-commits
- update dependencies & plugins

Lost of updates
